# Generated by Django 5.2.5 on 2025-08-09 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_color', models.CharField(default='#222222', max_length=16)),
                ('input_border_color', models.CharField(default='#cccccc', max_length=16)),
                ('button_color', models.CharField(default='#007bff', max_length=16)),
                ('button_text_color', models.CharField(default='#fff', max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
